### ISSUE TITLE
cabal build fails

### ISSUE THREAD

**Issue by thanacles** [ekmett/bytes#40]
When running cabal build, I get the following errors:

src/Data/Bytes/Put.hs:32:1: error:
    Failed to load interface for ‘Control.Monad.Reader’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Put.hs:34:1: error:
    Failed to load interface for ‘Control.Monad.RWS.Lazy’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Put.hs:35:1: error:
    Failed to load interface for ‘Control.Monad.RWS.Strict’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Put.hs:36:1: error:
    Failed to load interface for ‘Control.Monad.State.Lazy’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Put.hs:37:1: error:
    Failed to load interface for ‘Control.Monad.State.Strict’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Put.hs:38:1: error:
    Failed to load interface for ‘Control.Monad.Writer.Lazy’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Put.hs:39:1: error:
    Failed to load interface for ‘Control.Monad.Writer.Strict’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.
[4 of 5] Compiling Data.Bytes.Get   ( src/Data/Bytes/Get.hs, dist/build/Data/Bytes/Get.p_o )

src/Data/Bytes/Get.hs:31:1: error:
    Failed to load interface for ‘Control.Monad.Reader’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Get.hs:33:1: error:
    Failed to load interface for ‘Control.Monad.RWS.Lazy’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Get.hs:34:1: error:
    Failed to load interface for ‘Control.Monad.RWS.Strict’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Get.hs:35:1: error:
    Failed to load interface for ‘Control.Monad.State.Lazy’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Get.hs:36:1: error:
    Failed to load interface for ‘Control.Monad.State.Strict’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Get.hs:37:1: error:
    Failed to load interface for ‘Control.Monad.Writer.Lazy’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

src/Data/Bytes/Get.hs:38:1: error:
    Failed to load interface for ‘Control.Monad.Writer.Strict’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1’?
    Use -v to see a list of the files searched for.

I originally got this when trying to add the Linear library to my project:
cabal install Linear

Note: I'm pretty new to haskell and cabal so let me know if I left any valuable info out.

**Comment by glguy** [comment]
The problem is that "you haven't installed the profiling libraries for package ‘mtl-2.2.1’", but you are now trying to install the profiling libraries for linear. Perhaps you changed your global cabal.config to try and build them by default? To fix this you'll need to reinstall mtl (and probably its dependencies and more) with profiling libraries enabled, or stop trying to build profiling libraries.

**Comment by thanacles** [comment]
Yep that fixed it.  Sorry about that, and thanks for the help.
