### ISSUE TITLE
Hackage revision to bump time upper bound

### ISSUE THREAD

**Issue by bgamari** [ekmett/bytes#48]
It looks like the most recent release on Hackage (1.15.5) has `time>=1.2 && <1.9`.

**Comment by RyanGlScott** [comment]
Given that the current Hackage version is incompatible with GHC 8.8, I'm reluctant to do this. I'll keep this issue open as a reminder to release the next major version of `bytes`, which is 8.8-compatible.

**Comment by RyanGlScott** [comment]
This was resolved with the release of `bytes-0.16`.
