### ISSUE TITLE
bytesting-0.11 breaks on older GHCs.

### ISSUE THREAD

**Issue by phadej** [ekmett/bytes#52]
```
% cabal build -w ghc-7.10.3 --constraint='bytestring >=0.11' --allow-newer=bytestring
```

```
src/Data/Bytes/Serial.hs:291:3:
    Not in scope: data constructor ‘PS’
    Perhaps you meant ‘BS’ (imported from Data.ByteString.Internal)
```

with

```
source-repository-package
  type: git
  location: https://github.com/haskell/text
  tag: v1.2.4.1-rc1
```

CI doesn't test these. They are however easy to spot if you grep for `PS` constructor.

**Comment by phadej** [comment]
(a solution is to allow `bytestring-0.11` only with GHC-8.0+, which support PatternSynonyms).

**Comment by phadej** [comment]
FWIW, I could build `acme-kmett` with GHC-7.10.3 and `bytestring-0.11`, if you want to see what fails without going through packages one by one.

**Comment by RyanGlScott** [comment]
Oops! Good catch. Would using CPP like [this](https://github.com/ekmett/lens/commit/1debced4e9cb8b904b1f52c3ab10a551e40f3b2d#diff-700f6fcfab7d955dd35e76a01956c66b89cff9f681274163b6d60051229ef14dR217) be sufficient to fix this issue in a backwards-compatible manner?

> FWIW, I could build `acme-kmett` with GHC-7.10.3 and `bytestring-0.11`, if you want to see what fails without going through packages one by one.

I don't think there's a need to do all that. If I understand correctly, the only conditional API that we'd have to watch out for in `bytestring` is the use of the `PS` data constructor, correct?

**Comment by phadej** [comment]
Re `lens` patch, yes. 

Re, breakage, yeah. There is also removed modules, but those you should notice with any GHC (though again, none GHC on ci uses `bytestring-0.11`)

**Comment by RyanGlScott** [comment]
OK. In that case, I checked all of the code that I maintain, and I was fortunate in that `bytes` is the only `PS`-using library that I accidentally broke. I'll revert the Hackage revision I made for `bytes-0.17` to allow `bytestring-0.11` and submit a proper PR to add `bytestring-0.11` support momentarily.
